import{a as d,i as s}from"./assets/vendor-a23d62c7.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();d.defaults.headers.common["x-api-key"]="live_URYiUDVMJKnsTYSLnYWeR31PUeH8c5Yz2b0ev0a1MU6oS9U6mrAOkeE6lCc4s4wU";async function f(){return await d.get("https://api.thecatapi.com/v1/breeds").then(e=>e.data)}async function h(e){return await d.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`).then(r=>r.data)}const l=document.querySelector(".breed-select"),u=document.querySelector(".cat-info"),g=document.querySelector(".error"),c=document.querySelector(".loader");g.style.display="none";function p(e){e.style.display="block"}function m(e){e.style.display="none"}function y(e){u.innerHTML=`
    <div class="wrapper">
    <img class="cat-img" src="${e[0].url}" alt="Cat Image"/>
    <div>
    <h2>${e[0].breeds[0].name}</h2>
    <p><b>Description:</b> ${e[0].breeds[0].description}</p>
    <p><b>Temperament:</b> ${e[0].breeds[0].temperament}</p>
    </div>
    </div>
  `,p(u)}async function w(){const e=l.value;p(c);try{const r=await h(e);r.length===0?s.show({title:"Error",message:"❌ Oops! Something went wrong! Try reloading the page!",position:"topCenter",color:"red"}):y(r)}catch{s.show({title:"Error",message:"❌ Oops! Something went wrong! Try reloading the page!",position:"topCenter",color:"red"})}finally{m(c)}}async function b(){try{p(c);const e=await f();if(e){const r=e.map(i=>{const n=document.createElement("option");return n.value=i.id,n.textContent=i.name,n});l.append(...r),l.addEventListener("change",w)}else s.show({title:"Error",message:"❌ Oops! Something went wrong! Try reloading the page!",position:"topCenter",color:"red"})}catch{s.show({title:"Error",message:"❌ Oops! Something went wrong! Try reloading the page!",position:"topCenter",color:"red"})}finally{m(c)}}b();
//# sourceMappingURL=commonHelpers.js.map
