import{a as p,i as u}from"./assets/vendor-172f28d0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();p.defaults.headers.common["x-api-key"]="live_URYiUDVMJKnsTYSLnYWeR31PUeH8c5Yz2b0ev0a1MU6oS9U6mrAOkeE6lCc4s4wU";const i=document.querySelector(".breed-select"),f=document.querySelector(".cat-info"),c=document.querySelector(".loader"),m=document.querySelector(".error");m.style.display="none";function d(e){e.style.display="none"}function a(e){e.style.display="block"}async function h(){return a(c),d(i),await p.get("https://api.thecatapi.com/v1/breeds").then(e=>(a(i),e.data)).catch(()=>{u.show({title:"Error",message:"❌ Oops! Something went wrong! Try reloading the page!",position:"topCenter",color:"red"})}).finally(()=>d(c))}async function y(e){return a(c),await p.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`).then(r=>r.data).catch(()=>{u.show({title:"Error",message:"❌ Oops! Something went wrong! Try reloading the page!",position:"topCenter",color:"red"})}).finally(()=>d(c))}function g(e){f.innerHTML=`
    <div class="wrapper">
    <img class="cat-img" src="${e[0].url}" alt="Cat Image"/>
    <div>
    <h2>${e[0].breeds[0].name}</h2>
    <p><b>Description:</b> ${e[0].breeds[0].description}</p>
    <p><b>Temperament:</b> ${e[0].breeds[0].temperament}</p>
    </div>
    </div>
  `,a(f)}async function b(){const e=i.value,r=await y(e);if(r){if(r.length===0){u.show({title:"Error",message:"❌ Oops! Something went wrong! Try reloading the page!",position:"topCenter",color:"red"});return}}else return;g(r)}async function w(){const e=await h();if(!e)return;const r=e.map(s=>{const n=document.createElement("option");return n.value=s.id,n.textContent=s.name,n});i.append(...r),i.addEventListener("change",b)}w();
//# sourceMappingURL=commonHelpers.js.map
